config/routes.rb
Halisaa::Application.routes.draw do

  # Admin side
  devise_for :admins, controllers: { sessions: 'hq/sessions',  registrations: 'hq/registrations', passwords: 'hq/passwords' }, path: 'hq',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification'},
             :skip => [:registrations]
  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', :as => 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', :as => 'admin_registration'
  end
  namespace :hq do
    root to: 'dashboard#index'
    resource :admin_profile, except: [:destroy], path: 'profile'
    resources :audits, only: [:index, :show]
    resources :users, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
    resources :admins, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
    resources :companies, except: [:destroy] do
      post :block, on: :member
      post :unblock, on: :member
      post :sing_in, on: :member
      post :block_all, on: :collection
    end
  end

  # User side
  devise_for :users, controllers: { sessions: 'user/sessions',  registrations: 'user/registrations' }, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification'}
  namespace :user do
    resource :user_profile, except: [:destroy], path: 'profile', as: 'profile'
  end

  # Company side
  devise_for :companies, controllers: { sessions: 'company/sessions',  registrations: 'company/registrations' }, path: 'company',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification'}
  namespace :company do
    root to: 'dashboard#index'
    get 'edit_company' => 'company#edit', :as => 'edit'
    put 'update_company' => 'company#update', :as => 'update'
    resource :company_profile, except: [:destroy], path: 'profile', as: 'profile'
    resources :astroturves do
      get :timetable, on: :member
      get :detail, on: :member
    end
  end

  # General
  scope '(:locale)', :locale => /en|tr/ do
    root to: 'welcome#index'
    # get '/404' => 'errors#not_found'
    # get '/500' => 'errors#internal_server_error'
  end
  namespace :api do
    resources :cities, only: [:index, :show]
    resources :astroturves, only: [] do
      get 'timetables/index' => 'timetables#index', as: 'timetables_index'
    end
    namespace :company do
      resources :astroturves, only: [] do
        resource :timetables, only: [ :create, :update, :destroy]
        get 'timetables/index' => 'timetables#index', as: 'timetables_index'
      end
    end
  end

end

app/views/layouts/partials/_head.haml
%title
  - if content_for?(:title).present?
    = "#{yield(:title).capitalize.titleize} - Halisaa"
  -else
    Halisaa
%meta{:content => t('head.description'), :name => 'description'}/
%meta{:content => t('head.author'), :name => 'author'}/
%link(rel="icon" href="/favicon.ico")

app/views/layouts/partials/_messages.haml
- flash.each do |key, value|
  - if key.to_s == "notice"
    - key = "success"
  - if key.to_s == "alert"
    - key = "danger"
  %div{:class => "alert alert-dismissable alert-#{key}"}
    - if key.to_s == "danger" || key.to_s == "warning"
      %i.fa.fa-exclamation-triangle.fs-25
      %strong
        = t 'errors.message.sory'
        \!
    - else
      %i.fa.fa-smile-o.fs-25{:style => "padding: 0px 5px;"}
    = value

app/views/layouts/partials/_navbar.haml
.header.clearfix
  %nav
    %ul.nav.nav-pills.pull-right
      - if current_user
        %li.dropdown
          %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
            %i.fa.fa-user
            = current_user.email
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to edit_user_profile_path, class: 'btn btn-large' do
                %i.fa.fa-edit
                = t('navbar.edit_profile')
            %li
              = link_to edit_user_registration_path , class: 'btn btn-large' do
                %i.fa.fa-edit
                = t('navbar.edit_login_info')
            %li.dvider
            %li
              = link_to destroy_user_session_path, class: 'btn btn-large', method: :delete do
                %i.fa.fa-sign-out
                = t('navbar.logout')
      - elsif current_company
        -
      - else
        %li.dropdown{class: set_active([new_user_session_path, new_company_session_path]) }
          %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
            %i.fa.fa-sign-in
            = t('navbar.login')
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to new_user_session_path do
                %i.fa.fa-user
                = t('navbar.login_as_user')
            %li
              = link_to new_company_session_path do
                %i.fa.fa-building
                = t('navbar.login_as_company')

        %li.dropdown{class: set_active([new_user_registration_path, new_company_registration_path])}
          %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
            %i.fa.fa-user-plus
            = t('navbar.register')
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to new_user_registration_path do
                %i.fa.fa-user
                = t('navbar.signup_as_user')
            %li
              = link_to new_company_registration_path do
                %i.fa.fa-building
                = t('navbar.signup_as_company')
      -#%li.dropdown
      -#  %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
      -#    %i.fa.fa-flag
      -#    = t("navbar.language.#{I18n.locale}")
      -#    %b.caret
      -#  %ul.dropdown-menu
      -#    %li
      -#      = link_to locale: :tr  do
      -#        %i.fa.fa-flag
      -#        = t('navbar.language.tr')
      -#    %li
      -#      = link_to locale: :en  do
      -#        %i.fa.fa-flag
      -#        = t('navbar.language.en')
  %h3.text-muted
    = link_to 'Halisaa', root_path, class: 'text-muted'

app/views/layouts/partials/_trackers.haml
-#:javascript
-#  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
-#  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
-#  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
-#  s.parentNode.insertBefore(g,s)}(document,'script'));